#File options
files:
    include: 'app/scss/**/*.scss'
    ignore: 'app/scss/materialize-src/**/*.scss'

rules:
    indentation:
        - 1
        - size: 4
    leading-zero:
        - 0
        - include: false
    nesting-depth:
        - 2
        - max-depth: 4
